num_classes: 43
epochs: 40
grad_clip: -1
log_frequency: 50
criterion:
  name: CrossEntropyLoss
model:
  name: VGG16
  num_classes: $num_classes
optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 0.0005
  momentum: 0.9
scheduler:
  name: MultiStepLR
  milestones:
  - 35
  - 40
  gamma: 0.1
dataset:
  name: DatasetGenerator
  train_bs: 100
  eval_bs: 100
  n_workers: 4
  train_d_type: BadNetGTSRB
  test_d_type: GTSRB
  train_tf_op: GTSRB
  test_tf_op: GTSRB
  poison_rate: 0.025
  poison_test_d_type: BadNetGTSRB
  train_path: /data/projects/punim0784/datasets/
  test_path: /data/projects/punim0784/datasets/
